"""
explainer.py

Purpose: Generate rich, natural language biological explanations of
         pipeline results using Groq's hosted LLM API, grounded in the
         RAG knowledge base. This is the "brain" of the system —
         it turns raw statistics into bioinformatician-quality insights.

         Flow:
         pipeline_result + RAG context → Groq prompt → rich explanation

         Previously used Ollama (local LLM via subprocess). Swapped to
         Groq's free tier so the explainer can run on memory-constrained
         deployment hosts (e.g. Render free tier, 512MB RAM) where Ollama
         cannot run. Groq's free tier: https://console.groq.com/keys

Inputs:  Pipeline result object (QCResult, RNAseqResult, VariantResult)
         Optional: user follow-up question string
Outputs: Rich natural language explanation string

Author:  Emmanuel Ogbu (Manny)
Date:    2026-05-01
"""

import json
import os
from typing import Any

import requests

from bioagent.rag.retriever import BioRetriever
from bioagent.utils.logger import get_logger

logger = get_logger(__name__)

GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"

# Free-tier model — fast (LPU hardware), good quality for this use case.
# Override with the GROQ_MODEL env var if needed.
GROQ_MODEL = os.environ.get("GROQ_MODEL", "llama-3.3-70b-versatile")


def explain_results(
    pipeline_result: Any,
    pipeline_name: str,
    stats: dict,
    warnings: list[str],
    use_rag: bool = True
) -> str:
    """
    Generate a rich biological explanation of pipeline results using Groq.

    Queries the RAG knowledge base for relevant context, then passes
    the results + context to Groq to generate a natural language
    explanation that reads like a bioinformatician wrote it.

    Args:
        pipeline_result: The full pipeline result object.
        pipeline_name: Human-readable pipeline name (e.g. "FASTA QC Pipeline").
        stats: Dictionary of key statistics from the pipeline.
        warnings: List of QC warnings generated by the pipeline.
        use_rag: Whether to query RAG for additional context.

    Returns:
        Rich natural language explanation string from Groq.
        Falls back to basic interpretation if Groq is unavailable.
    """
    logger.info(f"Generating Groq explanation for: {pipeline_name}")

    # Step 1 — Build RAG context
    rag_context = ""
    if use_rag:
        try:
            retriever = BioRetriever()
            # Build query from pipeline name and key stats
            query = _build_rag_query(pipeline_name, stats)
            rag_context = retriever.retrieve_as_context(query, n_results=3)
            logger.info("RAG context retrieved successfully.")
        except Exception as e:
            logger.warning(f"RAG query failed, proceeding without context: {e}")

    # Step 2 — Build the prompt
    prompt = _build_prompt(pipeline_name, stats, warnings, rag_context)

    # Step 3 — Call Groq
    try:
        explanation = _call_groq(prompt)
        logger.info("Groq explanation generated successfully.")
        return explanation
    except Exception as e:
        logger.warning(f"Groq unavailable: {e}. Using basic interpretation.")
        return _fallback_explanation(pipeline_name, stats, warnings)


def answer_question(
    question: str,
    pipeline_name: str,
    stats: dict,
    interpretation: str
) -> str:
    """
    Answer a follow-up question about pipeline results using Groq.

    This enables the Q&A feature in the frontend — users can ask
    "Why is BRCA1 downregulated?" and Groq answers using the
    pipeline context.

    Args:
        question: The user's follow-up question.
        pipeline_name: Which pipeline produced the results.
        stats: Key statistics from the pipeline.
        interpretation: The original interpretation text.

    Returns:
        Groq's answer to the question as a string.
    """
    logger.info(f"Answering follow-up question: {question[:50]}...")

    # Get fresh RAG context relevant to the question
    rag_context = ""
    try:
        retriever = BioRetriever()
        rag_context = retriever.retrieve_as_context(question, n_results=2)
    except Exception as e:
        logger.warning(f"RAG query failed for Q&A: {e}")

    prompt = f"""You are an expert bioinformatician helping a researcher understand their data.

Pipeline used: {pipeline_name}
Key results: {json.dumps(stats, indent=2)}

Previous interpretation:
{interpretation}

Relevant knowledge:
{rag_context}

The researcher asks: {question}

Answer clearly and concisely in plain English. Focus on the biology.
Keep your answer under 150 words."""

    try:
        return _call_groq(prompt)
    except Exception as e:
        return f"Unable to answer question (Groq unavailable): {e}"


def _build_rag_query(pipeline_name: str, stats: dict) -> str:
    """
    Build a RAG query from pipeline name and statistics.

    Args:
        pipeline_name: Name of the pipeline.
        stats: Key statistics dictionary.

    Returns:
        Query string for RAG retrieval.
    """
    if "mean_gc" in stats:
        return (
            f"FASTA sequence quality control GC content "
            f"{stats.get('mean_gc', '')}% sequence analysis bioinformatics"
        )
    elif "upregulated_count" in stats:
        return (
            f"RNA-seq differential expression analysis "
            f"upregulated downregulated genes fold change "
            f"DESeq2 volcano plot PCA heatmap"
        )
    elif "pathogenic_count" in stats:
        return (
            f"variant calling annotation clinical significance "
            f"pathogenic SNP VCF genomics cancer"
        )
    else:
        return f"bioinformatics {pipeline_name} analysis interpretation"


def _build_prompt(
    pipeline_name: str,
    stats: dict,
    warnings: list[str],
    rag_context: str
) -> str:
    """
    Build the Groq prompt from pipeline results and RAG context.

    Args:
        pipeline_name: Name of the pipeline.
        stats: Key statistics from pipeline.
        warnings: QC warnings generated.
        rag_context: Retrieved knowledge chunks.

    Returns:
        Formatted prompt string for Groq.
    """
    warnings_text = "\n".join(warnings) if warnings else "No warnings."

    prompt = f"""You are an expert bioinformatician writing a clear analysis report.

A researcher has just run the {pipeline_name} on their data. Here are the results:

STATISTICS:
{json.dumps(stats, indent=2)}

QC WARNINGS:
{warnings_text}

RELEVANT KNOWLEDGE FROM LITERATURE:
{rag_context}

Write a clear, professional biological interpretation of these results.
Your explanation should:
1. State what the results mean in plain English
2. Highlight any concerning findings
3. Explain the biological significance
4. Suggest what to do next

Keep your response under 200 words. Write as if explaining to a PhD student."""

    return prompt


def _call_groq(prompt: str) -> str:
    """
    Call Groq's hosted chat-completions API and return the response.

    Groq serves open models (Llama 3.3, etc.) on custom LPU hardware,
    with a free tier that needs no local install — this is what lets
    the explainer run on a deployed server instead of only on a
    laptop with Ollama installed.

    Args:
        prompt: The full prompt string to send to the model.

    Returns:
        The model's response text.

    Raises:
        RuntimeError: If GROQ_API_KEY is missing or the request fails.
    """
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        raise RuntimeError(
            "GROQ_API_KEY not set. Get a free key at "
            "https://console.groq.com/keys and export it as an "
            "environment variable."
        )

    try:
        response = requests.post(
            GROQ_API_URL,
            headers={"Authorization": f"Bearer {api_key}"},
            json={
                "model": GROQ_MODEL,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.3,
            },
            timeout=30,
        )
        response.raise_for_status()
    except requests.exceptions.RequestException as e:
        raise RuntimeError(f"Groq API request failed: {e}")

    data = response.json()
    try:
        text = data["choices"][0]["message"]["content"].strip()
    except (KeyError, IndexError):
        raise RuntimeError(f"Unexpected Groq response shape: {data}")

    if not text:
        raise RuntimeError("Groq returned empty response.")

    return text


def _fallback_explanation(
    pipeline_name: str,
    stats: dict,
    warnings: list[str]
) -> str:
    """
    Generate a basic explanation when Groq is unavailable.

    Args:
        pipeline_name: Name of the pipeline.
        stats: Key statistics.
        warnings: QC warnings.

    Returns:
        Basic formatted explanation string.
    """
    lines = [
        f"Analysis complete: {pipeline_name}",
        "",
        "Key findings:",
    ]

    for key, value in stats.items():
        label = key.replace("_", " ").title()
        lines.append(f"  • {label}: {value}")

    lines.append("")
    lines.append("QC Assessment:")
    for w in warnings:
        lines.append(f"  • {w}")

    lines.append("")
    lines.append(
        "Note: Set GROQ_API_KEY for AI-powered biological interpretation. "
        "Get a free key at https://console.groq.com/keys"
    )

    return "\n".join(lines)