"""
explainer.py

Purpose: Generate rich, natural language biological explanations of
         pipeline results using Ollama (local LLM) grounded in the
         RAG knowledge base. This is the "brain" of the system —
         it turns raw statistics into bioinformatician-quality insights.

         Flow:
         pipeline_result + RAG context → Ollama prompt → rich explanation

Inputs:  Pipeline result object (QCResult, RNAseqResult, VariantResult)
         Optional: user follow-up question string
Outputs: Rich natural language explanation string

Author:  Emmanuel Ogbu (Manny)
Date:    2026-05-01
"""

import subprocess
import json
from typing import Any

from bioagent.rag.retriever import BioRetriever
from bioagent.utils.logger import get_logger

logger = get_logger(__name__)

# Model to use — llama3.2:3b runs on your i5 with 16GB RAM
# Responses take 10-30 seconds locally — acceptable for demo
OLLAMA_MODEL = "llama3.2:3b"


def explain_results(
    pipeline_result: Any,
    pipeline_name: str,
    stats: dict,
    warnings: list[str],
    use_rag: bool = True
) -> str:
    """
    Generate a rich biological explanation of pipeline results using Ollama.

    Queries the RAG knowledge base for relevant context, then passes
    the results + context to Ollama to generate a natural language
    explanation that reads like a bioinformatician wrote it.

    Args:
        pipeline_result: The full pipeline result object.
        pipeline_name: Human-readable pipeline name (e.g. "FASTA QC Pipeline").
        stats: Dictionary of key statistics from the pipeline.
        warnings: List of QC warnings generated by the pipeline.
        use_rag: Whether to query RAG for additional context.

    Returns:
        Rich natural language explanation string from Ollama.
        Falls back to basic interpretation if Ollama unavailable.
    """
    logger.info(f"Generating Ollama explanation for: {pipeline_name}")

    # Step 1 — Build RAG context
    rag_context = ""
    if use_rag:
        try:
            retriever = BioRetriever()
            # Build query from pipeline name and key stats
            query = _build_rag_query(pipeline_name, stats)
            rag_context = retriever.retrieve_as_context(query, n_results=3)
            logger.info("RAG context retrieved successfully.")
        except Exception as e:
            logger.warning(f"RAG query failed, proceeding without context: {e}")

    # Step 2 — Build the prompt
    prompt = _build_prompt(pipeline_name, stats, warnings, rag_context)

    # Step 3 — Call Ollama
    try:
        explanation = _call_ollama(prompt)
        logger.info("Ollama explanation generated successfully.")
        return explanation
    except Exception as e:
        logger.warning(f"Ollama unavailable: {e}. Using basic interpretation.")
        return _fallback_explanation(pipeline_name, stats, warnings)


def answer_question(
    question: str,
    pipeline_name: str,
    stats: dict,
    interpretation: str
) -> str:
    """
    Answer a follow-up question about pipeline results using Ollama.

    This enables the Q&A feature in the frontend — users can ask
    "Why is BRCA1 downregulated?" and Ollama answers using the
    pipeline context.

    Args:
        question: The user's follow-up question.
        pipeline_name: Which pipeline produced the results.
        stats: Key statistics from the pipeline.
        interpretation: The original interpretation text.

    Returns:
        Ollama's answer to the question as a string.
    """
    logger.info(f"Answering follow-up question: {question[:50]}...")

    # Get fresh RAG context relevant to the question
    rag_context = ""
    try:
        retriever = BioRetriever()
        rag_context = retriever.retrieve_as_context(question, n_results=2)
    except Exception as e:
        logger.warning(f"RAG query failed for Q&A: {e}")

    prompt = f"""You are an expert bioinformatician helping a researcher understand their data.

Pipeline used: {pipeline_name}
Key results: {json.dumps(stats, indent=2)}

Previous interpretation:
{interpretation}

Relevant knowledge:
{rag_context}

The researcher asks: {question}

Answer clearly and concisely in plain English. Focus on the biology.
Keep your answer under 150 words."""

    try:
        return _call_ollama(prompt)
    except Exception as e:
        return f"Unable to answer question (Ollama unavailable): {e}"


def _build_rag_query(pipeline_name: str, stats: dict) -> str:
    """
    Build a RAG query from pipeline name and statistics.

    Args:
        pipeline_name: Name of the pipeline.
        stats: Key statistics dictionary.

    Returns:
        Query string for RAG retrieval.
    """
    if "mean_gc" in stats:
        return (
            f"FASTA sequence quality control GC content "
            f"{stats.get('mean_gc', '')}% sequence analysis bioinformatics"
        )
    elif "upregulated_count" in stats:
        return (
            f"RNA-seq differential expression analysis "
            f"upregulated downregulated genes fold change "
            f"DESeq2 volcano plot PCA heatmap"
        )
    elif "pathogenic_count" in stats:
        return (
            f"variant calling annotation clinical significance "
            f"pathogenic SNP VCF genomics cancer"
        )
    else:
        return f"bioinformatics {pipeline_name} analysis interpretation"


def _build_prompt(
    pipeline_name: str,
    stats: dict,
    warnings: list[str],
    rag_context: str
) -> str:
    """
    Build the Ollama prompt from pipeline results and RAG context.

    Args:
        pipeline_name: Name of the pipeline.
        stats: Key statistics from pipeline.
        warnings: QC warnings generated.
        rag_context: Retrieved knowledge chunks.

    Returns:
        Formatted prompt string for Ollama.
    """
    warnings_text = "\n".join(warnings) if warnings else "No warnings."

    prompt = f"""You are an expert bioinformatician writing a clear analysis report.

A researcher has just run the {pipeline_name} on their data. Here are the results:

STATISTICS:
{json.dumps(stats, indent=2)}

QC WARNINGS:
{warnings_text}

RELEVANT KNOWLEDGE FROM LITERATURE:
{rag_context}

Write a clear, professional biological interpretation of these results.
Your explanation should:
1. State what the results mean in plain English
2. Highlight any concerning findings
3. Explain the biological significance
4. Suggest what to do next

Keep your response under 200 words. Write as if explaining to a PhD student."""

    return prompt


def _call_ollama(prompt: str) -> str:
    """
    Call Ollama locally via subprocess and return the response.

    Uses subprocess instead of HTTP to avoid dependency on Ollama's
    Python client version. The ollama CLI is always available after
    installation regardless of package version.

    Args:
        prompt: The full prompt string to send to Ollama.

    Returns:
        Ollama's response text.

    Raises:
        RuntimeError: If Ollama is not installed or model not found.
    """
    try:
        # Call ollama CLI directly — most reliable method on Windows
        result = subprocess.run(
            ["ollama", "run", OLLAMA_MODEL, prompt],
            capture_output=True,
            text=True,
            timeout=120,
            encoding="utf-8",
            errors="replace"
        )

        if result.returncode != 0:
            raise RuntimeError(f"Ollama error: {result.stderr}")

        response = result.stdout.strip()

        # Remove ANSI escape codes — Ollama CLI outputs these for terminal
        # animation which corrupt the text when captured via subprocess
        import re
        response = re.sub(r'\x1b\[[0-9;]*[a-zA-Z]', '', response)
        response = re.sub(r'\[[0-9]+[A-Z]', '', response)
        response = response.strip()

        if not response:
            raise RuntimeError("Ollama returned empty response.")

        return response

    except FileNotFoundError:
        raise RuntimeError(
            "Ollama not found. Install from https://ollama.com/download "
            "and run: ollama pull llama3.2:3b"
        )
    except subprocess.TimeoutExpired:
        raise RuntimeError("Ollama timed out after 2 minutes.")


def _fallback_explanation(
    pipeline_name: str,
    stats: dict,
    warnings: list[str]
) -> str:
    """
    Generate a basic explanation when Ollama is unavailable.

    Args:
        pipeline_name: Name of the pipeline.
        stats: Key statistics.
        warnings: QC warnings.

    Returns:
        Basic formatted explanation string.
    """
    lines = [
        f"Analysis complete: {pipeline_name}",
        "",
        "Key findings:",
    ]

    for key, value in stats.items():
        label = key.replace("_", " ").title()
        lines.append(f"  • {label}: {value}")

    lines.append("")
    lines.append("QC Assessment:")
    for w in warnings:
        lines.append(f"  • {w}")

    lines.append("")
    lines.append(
        "Note: Install Ollama for AI-powered biological interpretation. "
        "Visit https://ollama.com/download"
    )

    return "\n".join(lines)